# Generated by Django 4.1.5 on 2023-02-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_advisors', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='fin_advisor_username',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
