# Generated by Django 4.1.5 on 2023-02-06 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_advisors', '0003_alter_booking_fin_advisor_username_alter_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
