# Generated by Django 4.1.5 on 2023-02-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_advisors', '0004_booking_booking_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
